export const iconModuleFaceDetectionPath = './src/assets/images/module-face-detection.jpg'
export const iconModuleFaceRecognitionPath = './src/assets/images/module-face-recognition.jpg'
export const iconModuleFaceMaskIdentificationPath = './src/assets/images/module-face-mask-identification.jpg'
export const iconModuleLicensePlateRecognitionPath = './src/assets/images/module-license-platen-recognition.jpg'
export const iconModuleEnglishDigitPredictionPath = './src/assets/images/module-english-digit-prediction.jpg'
export const iconModuleVietnameseDigitPredictionPath = './src/assets/images/module-vietnamese-digit-prediction.jpg'
export const iconModuleCalifoniaHousePricePredictionPath = './src/assets/images/module-califonia-house-price-prediction.jpg'
export const iconModuleAnimalClassificationPath = './src/assets/images/module-animal-classification.jpg'
export const iconModuleFruitClassificationPath = './src/assets/images/module-fruit-classification.jpg'

export const exampleModuleFaceDetectionPath = './src/assets/images/example-face-detection.jpg'
export const exampleModuleFaceRecognitionPath = './src/assets/images/example-face-recognition.jpg'
